### ISSUE TITLE
This is great, but expose an api so i can pass redis/ memcached etc.

### ISSUE THREAD

**Issue by kevbook** [3rd-Eden/expirable#2]

**Comment by 3rd-Eden** [comment]
This is unfortunately not the scope of the project. This is only for in-memory caching in your node process. If you want to a cache layer that supports multiple and network based transports I suggest you to take a look at @swaagie's dynamis;  https://github.com/Moveo/dynamis

**Comment by kevbook** [comment]
Thank you, I love all your work (the simplicity of code/ lightweight & performance oriented)

**Comment by Swaagie** [comment]
Note that dynamis is still under heavy development though, for instance it needs a ttl
